// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mihtlaxbqhizbcdyyevy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1paHRsYXhicWhpemJjZHl5ZXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3NDk1MzksImV4cCI6MjA4NTMyNTUzOX0.NhzzZNmMclUa3LXCv_0e1yJ5bJr3KQiFbwEahtxH0_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});